DROP DATABASE IF EXISTS Kalum_Test;
go
CREATE DATABASE Kalum_Test
go
USE Kalum_Test
CREATE TABLE ExamenAdmision
(
	ExamenId VARCHAR(128) PRIMARY KEY NOT NULL,
	FechaExamen DATETIME NOT NULL
)
go
CREATE TABLE CarreraTecnica
(
	CarreraId VARCHAR(128) PRIMARY KEY NOT NULL,
	Nombre VARCHAR(128) NOT NULL
)
go
CREATE TABLE Jornada
(
	JornadaId VARCHAR(128) PRIMARY KEY NOT NULL,
	JornadaTipo VARCHAR(2) NOT NULL, 
	DescripcionJornada VARCHAR(128) NOT NULL
)
go
CREATE TABLE Aspirante
(
	NoExpediente VARCHAR(128) PRIMARY KEY NOT NULL,
	Apellidos VARCHAR(128) NOT NULL,
	Nombres VARCHAR(128) NOT NULL,
	Direccion VARCHAR(128) NOT NULL,
	Telefono VARCHAR(64) NOT NULL,
	Email VARCHAR(128) NOT NULL UNIQUE,
	Estatus VARCHAR(32) DEFAULT 'NO ASIGNADO',
	CarreraId VARCHAR(128) NOT NULL,
	ExamenId VARCHAR(128) NOT NULL,
	JornadaId VARCHAR(128) NOT NULL,
	CONSTRAINT FK_ASPIRANTE_CARRERA_TECNICA FOREIGN KEY (CarreraId) REFERENCES CarreraTecnica(CarreraId),
	CONSTRAINT FK_ASPIRANTE_EXAMEN_ADMISION FOREIGN KEY (ExamenId) REFERENCES ExamenAdmision(ExamenId),
	CONSTRAINT FK_ASPIRANTE_JORNADA FOREIGN KEY (JornadaId) REFERENCES Jornada(JornadaId),
)
go
CREATE TABLE ResultadoExamenAdmision
(
	NoExpediente VARCHAR(128) NOT NULL,
	Anio VARCHAR(4) NOT NULL,
	DescripcionResultado VARCHAR(128) NOT NULL,
	Nota INT DEFAULT 0,
	PRIMARY KEY (NoExpediente,Anio),
	CONSTRAINT FK_RESULTADO_EXAMEN_ADMISION_ASPIRANTE FOREIGN KEY (NoExpediente) REFERENCES Aspirante(NoExpediente)
)
go
CREATE TABLE InscripcionPago
(
	BoletaPago VARCHAR(128) NOT NULL,
	FechaPago DATETIME NOT NULL,
	Monto DECIMAL(10,2) NOT NULL,
	Anio VARCHAR(4) NOT NULL,
	NoExpediente VARCHAR(128) NOT NULL,
	PRIMARY KEY (BoletaPago, Anio, NoExpediente),
	CONSTRAINT FK_INSCRIPCION_PAGO_ASPIRANTE FOREIGN KEY (NoExpediente) REFERENCES Aspirante(NoExpediente)
)
go
CREATE TABLE InversionCarreraTecnica
(
	InversionId VARCHAR(128) PRIMARY KEY NOT NULL,
	MontoInscripcion DECIMAL(10,2) NOT NULL,
	NumeroPagos INT NOT NULL,
	MontoPago DECIMAL(10,2) NOT NULL,
	CarreraId VARCHAR(128) NOT NULL,
	CONSTRAINT FK_INVERSION_CARRERA_TECNICA FOREIGN KEY (CarreraId) REFERENCES CarreraTecnica(CarreraId)
)
go
CREATE TABLE Alumno
(
	Carne VARCHAR(8) PRIMARY KEY NOT NULL,
	Apellidos VARCHAR(128) NOT NULL,
	Nombres VARCHAR(128) NOT NULL,
	Direccion VARCHAR(128) NOT NULL,
	Telefono VARCHAR(64) NOT NULL,
	Email VARCHAR(64) NOT NULL
)
go
CREATE TABLE Inscripcion
(
	InscripcionId VARCHAR(128) PRIMARY KEY NOT NULL,
	Ciclo VARCHAR(4) NOT NULL,
	FechaInscripcion DATETIME NOT NULL,
	Carne VARCHAR(8),
	CarreraId VARCHAR(128),
	JornadaId VARCHAR(128),
	CONSTRAINT FK_INSCRIPCION_ALUMNO FOREIGN KEY (Carne) REFERENCES Alumno(Carne),
	CONSTRAINT FK_INSCRIPCION_CARRERA_TECNICA FOREIGN KEY (CarreraId) REFERENCES CarreraTecnica(CarreraId),
	CONSTRAINT FK_INSCRIPCION_JORNADA FOREIGN KEY (JornadaId) REFERENCES Jornada(JornadaId),
)
go
CREATE TABLE Cargo
(
	CargoId VARCHAR(128) PRIMARY KEY NOT NULL,
	Descripcion VARCHAR(128) NOT NULL,
	Prefijo VARCHAR(64) NOT NULL,
	Monto DECIMAL(10,2) NOT NULL,
	GenerarMora BIT NOT NULL DEFAULT 1,
	PorcentajeMora INT NOT NULL,
)
go
CREATE TABLE CuentaPorCobrar
(
	CuentaId VARCHAR(128) PRIMARY KEY NOT NULL,
	AnioCuenta VARCHAR(4) NOT NULL,
	DescripcionCuenta VARCHAR(128) NOT NULL,
	FechaCargo DATETIME NOT NULL,
	FechaAplica DATETIME NOT NULL,
	MontoCargo DECIMAL(10,2) NOT NULL,
	Mora DECIMAL(10,2) NOT NULL,
	Descuento DECIMAL(10,2) NOT NULL,
	Carne VARCHAR(8) NOT NULL,
	CargoId VARCHAR(128) NOT NULL,
	CONSTRAINT FK_CUENTAS_POR_COBRAR_CARNE FOREIGN KEY (Carne) REFERENCES Alumno(Carne),
	CONSTRAINT FK_CUENTAS_POR_COBRAR_CARGO FOREIGN KEY (CargoId) REFERENCES Cargo(CargoId)
)